(move default_l fridge_l)
(open fridge fridge_l)
(pick bread fridge fridge_l)
(move fridge_l counter_1_l)
(put bread counter_1 counter_1_l)
(pick knife counter_1 counter_1_l)
(slice bread counter_1_l)
(put knife counter_1 counter_1_l)
(pick bread counter_1 counter_1_l)
(put bread toaster counter_1_l)
(turn_on toaster counter_1_l)
(pick bread toaster counter_1_l)
(move counter_1_l dining_table_l)
(put bread plate dining_table_l)
; cost = 14 (unit cost)
