(open fridge default_l)
(pick bread fridge default_l)
(put bread counter_1 default_l)
(pick knife counter_1 default_l)
(slice bread default_l)
(put knife bread default_l)
(pick bread counter_1 default_l)
(put bread toaster default_l)
(turn_on toaster default_l)
(pick bread toaster default_l)
(put bread plate default_l)
; cost = 11 (unit cost)
