import numpy as np
from base import PandaArm
import time


class Manipulator(PandaArm):
    def __init__(self, p, pandaId):
        super().__init__(p, pandaId)

    def is_moving(self,):
        '''
        checks if the manipulator is steady or still in motion
        returns
            moving : bool - ?(manipulator_moving)
        '''
        # TODO

    def move_joints(self, target_joints:list):
        '''
        moves manipulator joints to target joint poses
        args
            target_joints : 7D list of target joint angles
        '''
        # TODO

    def move_home(self,):
        '''
        moves robot to home position
        '''
        # TODO

    def move_in_task_space(self, target_position, target_orientation):
        '''
        moves robot end effector to target pose
        args
            target_position : 3D spatial location
            target_orientation : 3D orientation
        '''
        # TODO
    
    def command_gripper(self, open:bool):
        '''
        args
            open: do we want the robot to open its fingers, otherwise close them
        returns
            bool (success/failure)

        This function will simply close or open robots gripper, so to grasp or release the object
        '''
        # TODO

    def pick_object_from(self, obj_location:list, obj_orientation:list):
        '''
        perform pick operation for object placed at obj_location, obj_orientation
        args
            obj_location : object location
            obj_orientation : object orienation in euler notation
        '''
        # TODO

    def place_object_at(self, target_location:list, target_orientation:list):
        '''
        places the grasped object at target location in target orientation
        '''
        # TODO

    def execute_task_plan(self, plan:list):
        '''
        executes a task plan generated by the planner
        args
            plan : list of manipulator executable action steps
        '''
        # TODO