(move default_l fridge_l)
(open fridge fridge_l)
(pick bread fridge fridge_l)
(move fridge_l counter_1_l)
(put bread counter_1 counter_1_l)
(pick knife counter_1 counter_1_l)
(slice bread counter_1_l)
(put knife counter_1 counter_1_l)
(pick bread counter_1 counter_1_l)
(put bread toaster counter_1_l)
(turn_on toaster counter_1_l)
(pick bread toaster counter_1_l)
(move counter_1_l dining_table_l)
(put bread plate dining_table_l)
(move dining_table_l counter_2_l)
(pick mug counter_2 counter_2_l)
(move counter_2_l counter_1_l)
(put mug coffeemachine counter_1_l)
(turn_on coffeemachine counter_1_l)
(pick mug coffeemachine counter_1_l)
(move counter_1_l dining_table_l)
(put mug dining_table dining_table_l)
(move dining_table_l fridge_l)
(pick egg fridge fridge_l)
(move fridge_l counter_2_l)
(put egg pan counter_2_l)
(pick pan counter_2 counter_2_l)
(put pan stoveburner counter_2_l)
(turn_on stoveburner counter_2_l)
(pick pan stoveburner counter_2_l)
(move counter_2_l dining_table_l)
(put pan dining_table dining_table_l)
; cost = 32 (unit cost)
